### ISSUE TITLE
Issue on page /Calc1-Lab2-Derivatives.html

### ISSUE THREAD

**Issue by flideros** [sean-fitzpatrick/CalcLabs#1]
I could not get the bisection function to work so I added numpy and got this version to work:
 ```
def bisection(f, a, b, N):
    if f(a) * f(b) >= 0:
        print("Bisection method fails.")
        return None
    a_n, b_n = a, b
    for n in range(1, N + 1):
        m_n = (a_n + b_n) / 2
        f_m_n = f(m_n)
        if f(a_n) * f_m_n < 0:
            b_n = m_n
        elif f(b_n) * f_m_n < 0:
            a_n = m_n
        elif f_m_n == 0:
            print("Found exact solution.")
            return m_n
        else:
            print("Bisection method fails.")
            return None
    return (a_n + b_n) / 2

# Define f using sympy and numpy
f = sy.lambdify(x, x - sy.cos(x), 'numpy')

# Use the bisection method
result = bisection(f, 0, np.pi/2, 8)
print(result)

```

**Comment by sean-fitzpatrick** [comment]
The point here, as noted in the instructions below the program, is for the student to define a function using NumPy.

So the student is expected to take the extra step of adding a cell where they might, for example, write something like
```
import numpy as np
def f(x):
    return x-np.cos(x)
bisection(f,0,np.pi/2,8)
```

**Comment by flideros** [comment]
Thanks. I realized that after the fact that my solution was one approach, but not the solution. I just jumped into the derivatives NB before reading the preceding notebooks. I'm coming from F-sharp and WPF and started reading the Martin Fitzpatrick book on PyQt6 for about a month now.
